/*******************************************************************************
 * Copyright (c) 2016-2021 Institute of Legal Information and Judicial Systems IGSG-CNR (formerly ITTIG-CNR)
 * 
 * This program and the accompanying materials  are made available under the terms of the GNU General Public
 * License as published by the Free Software Foundation; either version 3 of the License, or (at your option)
 * any later version. 
 * You may not use this work except in compliance with the Licence.
 * You may obtain a copy of the Licence at: https://www.gnu.org/licenses/gpl-3.0.txt
 * Unless required by applicable law or agreed to in writing, software distributed under the Licence is 
 * distributed on an "AS IS" basis, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the Licence for the specific language governing permissions and limitations under the Licence.
 *  
 * Authors: Lorenzo Bacci (IGSG-CNR)
 ******************************************************************************/
/* The following code was generated by JFlex 1.6.1 */

package it.cnr.igsg.linkoln.service.impl.it;

import java.io.IOException;
import java.io.StringReader;

import it.cnr.igsg.linkoln.entity.*;
import it.cnr.igsg.linkoln.service.*;

import it.cnr.igsg.linkoln.service.impl.Util;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>Stopwords.jflex</tt>
 */
public class Stopwords extends LinkolnAnnotationService {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int lkn = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\0\1\2\1\0\1\0\1\1\22\0\1\14\5\0\1\6"+
    "\1\5\1\0\1\0\2\0\1\14\1\3\1\54\1\55\1\53\1\53"+
    "\1\53\1\53\1\53\1\53\1\53\1\53\1\53\1\53\1\15\1\13"+
    "\5\0\1\26\1\10\1\40\1\61\1\36\1\72\1\30\1\70\1\50"+
    "\1\23\1\64\1\57\1\23\1\7\1\52\1\12\1\23\1\32\1\24"+
    "\1\44\1\42\1\34\1\23\1\23\1\23\1\23\1\65\1\0\1\66"+
    "\1\0\1\4\1\5\1\25\1\20\1\37\1\60\1\35\1\71\1\27"+
    "\1\67\1\47\1\16\1\63\1\56\1\16\1\17\1\51\1\22\1\16"+
    "\1\31\1\21\1\43\1\41\1\33\1\16\1\16\1\16\1\16\12\0"+
    "\1\0\44\0\1\0\5\0\1\0\3\0\1\5\5\0\1\0\5\0"+
    "\1\16\1\16\4\16\1\0\1\16\1\45\1\45\2\16\1\16\1\16"+
    "\2\16\1\0\1\16\1\16\1\16\3\16\2\0\1\16\1\16\2\16"+
    "\3\0\1\16\1\16\4\16\1\0\1\16\1\45\1\45\2\16\1\16"+
    "\1\16\2\16\1\0\1\16\1\16\1\16\3\16\2\0\1\16\1\16"+
    "\2\16\53\0\1\16\1\16\6\0\2\46\66\0\1\16\1\16\4\0"+
    "\1\16\1\16\17\0\1\11\u1c88\0\1\16\1\16\216\0\2\16\42\0"+
    "\1\16\1\16\u0144\0\1\14\20\0\1\3\1\3\4\0\1\5\16\0"+
    "\1\0\1\0\u0100\0\1\62\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udee5\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\6\1\2\2\25\0\2\3\1\0\1\3\12\0"+
    "\2\4\2\0\1\5\1\6\4\0\1\7\7\0\2\10"+
    "\1\0\1\10\7\0\2\11\1\12\1\0\2\13\2\14"+
    "\2\0\2\15\2\16\1\0\1\16\15\0\2\17\1\20"+
    "\2\21\2\22\12\0\1\23\1\24\1\25\2\0\1\26"+
    "\21\0\1\27\4\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[148];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\73\0\166\0\261\0\354\0\u0127\0\u0162\0\u019d"+
    "\0\u0162\0\u01d8\0\u0213\0\u024e\0\u0289\0\u02c4\0\u02ff\0\u033a"+
    "\0\u0375\0\u03b0\0\u03eb\0\u0426\0\u0461\0\u049c\0\166\0\u04d7"+
    "\0\u0512\0\u054d\0\u0588\0\u05c3\0\u05fe\0\u0639\0\u0674\0\u0162"+
    "\0\u06af\0\u06ea\0\u0725\0\u0725\0\u0760\0\u079b\0\u07d6\0\u0811"+
    "\0\u084c\0\u0887\0\u08c2\0\u08fd\0\u0938\0\u0162\0\u0973\0\u09ae"+
    "\0\u09e9\0\u0938\0\u0a24\0\u0a5f\0\u0a9a\0\u0a24\0\u0ad5\0\u0162"+
    "\0\u0b10\0\u0b4b\0\u0b86\0\u0bc1\0\u0bfc\0\u0c37\0\u0c72\0\u0162"+
    "\0\u0cad\0\u0ce8\0\u0d23\0\u0d23\0\u0d5e\0\u0d99\0\u0dd4\0\u0e0f"+
    "\0\u0e4a\0\u0e85\0\u0162\0\u0ec0\0\u0efb\0\u0efb\0\u0162\0\u0f36"+
    "\0\u0162\0\u0f71\0\u0fac\0\u0fe7\0\u0162\0\u1022\0\u0162\0\u105d"+
    "\0\u1098\0\u10d3\0\u10d3\0\u110e\0\u1149\0\u1184\0\u11bf\0\u11fa"+
    "\0\u1235\0\u1270\0\u12ab\0\u12e6\0\u1321\0\u135c\0\u1397\0\u0162"+
    "\0\u13d2\0\u0725\0\u0162\0\u140d\0\u0162\0\u1448\0\u1483\0\u14be"+
    "\0\u14f9\0\u1534\0\u156f\0\u15aa\0\u15e5\0\u1620\0\u165b\0\u1696"+
    "\0\u0162\0\u08fd\0\u0d23\0\u16d1\0\u170c\0\u10d3\0\u1747\0\u1782"+
    "\0\u17bd\0\u17f8\0\u1833\0\u186e\0\u18a9\0\u18e4\0\u191f\0\u195a"+
    "\0\u1995\0\u19d0\0\u1a0b\0\u1a46\0\u1a81\0\u1abc\0\u1af7\0\u0162"+
    "\0\u1b32\0\u1b6d\0\u1ba8\0\u1be3";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[148];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\3\3\1\6\2\7\1\3\1\7"+
    "\1\3\1\5\1\3\30\7\1\3\5\7\2\3\4\7"+
    "\1\3\2\7\1\10\1\3\4\7\65\11\1\12\5\11"+
    "\7\0\1\13\1\0\1\14\1\15\4\0\1\13\1\0"+
    "\1\14\1\15\1\0\1\14\2\16\2\17\6\0\2\20"+
    "\2\21\2\22\1\0\3\23\2\24\3\0\2\25\2\26"+
    "\7\0\2\22\2\0\1\27\4\0\1\13\1\0\1\14"+
    "\1\15\4\0\1\13\1\0\1\14\1\15\1\0\1\14"+
    "\2\16\2\17\6\0\2\20\2\21\2\22\1\0\3\23"+
    "\2\24\3\0\2\25\2\26\7\0\2\22\7\0\1\30"+
    "\1\0\1\14\1\15\4\0\1\30\1\0\1\14\1\15"+
    "\1\0\1\14\2\16\2\17\4\0\2\31\2\20\2\21"+
    "\2\22\1\0\3\23\2\24\3\0\2\25\2\26\7\0"+
    "\2\22\7\0\1\32\1\0\1\14\1\15\4\0\1\32"+
    "\1\0\1\14\1\15\1\0\1\14\2\16\2\17\6\0"+
    "\2\20\2\21\2\22\1\0\3\23\2\24\3\0\2\25"+
    "\2\26\7\0\2\22\102\0\1\13\1\0\1\14\1\15"+
    "\4\0\1\13\1\0\1\14\1\15\1\0\1\14\2\16"+
    "\2\17\6\0\2\20\2\21\2\22\1\0\3\23\2\24"+
    "\3\0\2\33\2\26\7\0\2\22\55\0\1\34\52\0"+
    "\2\35\75\0\2\36\65\0\2\37\34\0\1\40\1\41"+
    "\5\40\2\0\1\40\1\0\3\40\11\0\2\42\15\0"+
    "\1\43\2\44\4\0\1\40\2\45\2\0\1\40\2\0"+
    "\2\40\62\0\2\46\54\0\2\47\6\0\2\50\14\0"+
    "\2\51\11\0\1\52\7\0\1\52\104\0\2\53\47\0"+
    "\1\54\7\0\1\54\36\0\2\55\13\0\1\56\1\57"+
    "\5\56\2\0\1\56\1\60\3\56\4\0\1\60\10\0"+
    "\2\61\11\0\1\56\6\0\1\56\4\0\1\56\2\0"+
    "\2\56\11\0\1\62\17\0\2\55\6\0\2\55\12\0"+
    "\2\55\25\0\1\63\17\0\2\64\6\0\2\65\7\0"+
    "\3\66\57\0\2\35\12\0\2\67\22\0\1\70\3\0"+
    "\1\71\5\0\1\70\43\0\2\72\21\0\1\73\7\0"+
    "\1\73\14\0\2\35\41\0\1\62\17\0\2\55\6\0"+
    "\2\55\12\0\2\55\7\0\3\74\64\0\2\75\42\0"+
    "\2\76\15\0\3\54\5\0\2\77\13\0\1\100\1\101"+
    "\5\100\2\0\1\100\1\0\3\100\11\0\2\102\15\0"+
    "\1\103\2\104\4\0\1\100\2\105\2\0\1\100\2\0"+
    "\2\100\35\0\2\106\42\0\1\40\146\0\2\107\13\0"+
    "\1\40\1\41\5\40\2\0\1\40\1\0\3\40\30\0"+
    "\1\40\6\0\1\40\4\0\1\40\2\0\2\40\4\0"+
    "\1\40\1\41\5\40\2\0\1\40\1\0\3\40\30\0"+
    "\1\40\6\0\1\40\2\110\2\0\1\40\2\0\2\40"+
    "\52\0\3\55\70\0\3\111\31\0\1\112\7\0\1\112"+
    "\36\0\2\112\50\0\2\111\34\0\1\113\1\114\3\113"+
    "\1\115\1\113\2\0\1\113\1\0\3\113\7\0\2\116"+
    "\17\0\1\113\2\0\2\116\2\0\1\113\4\0\1\113"+
    "\2\0\2\113\31\0\2\106\44\0\1\117\1\120\5\117"+
    "\2\0\1\117\1\0\3\117\30\0\1\117\6\0\1\117"+
    "\4\0\1\117\2\0\2\117\4\0\1\121\1\122\5\121"+
    "\2\0\1\121\1\0\3\121\30\0\1\121\6\0\1\121"+
    "\4\0\1\121\2\0\2\121\6\0\1\56\102\0\1\123"+
    "\7\0\1\123\103\0\2\124\36\0\1\125\1\126\5\125"+
    "\2\0\1\125\1\0\3\125\30\0\1\125\6\0\1\125"+
    "\4\0\1\125\2\0\2\125\4\0\1\127\1\130\5\127"+
    "\2\0\1\127\1\0\3\127\11\0\2\131\15\0\1\132"+
    "\2\133\4\0\1\127\2\134\2\0\1\127\2\0\2\127"+
    "\33\0\2\135\15\0\3\66\5\0\2\136\22\0\1\137"+
    "\7\0\1\137\62\0\1\140\7\0\1\140\55\0\1\70"+
    "\3\0\1\71\5\0\1\70\67\0\1\141\7\0\1\141"+
    "\2\0\1\141\55\0\1\142\7\0\1\142\135\0\3\143"+
    "\64\0\2\144\13\0\1\117\1\120\5\117\2\0\1\117"+
    "\1\0\3\117\30\0\1\117\6\0\1\117\2\145\2\0"+
    "\1\117\2\0\2\117\6\0\1\100\146\0\2\146\13\0"+
    "\1\100\1\101\5\100\2\0\1\100\1\0\3\100\30\0"+
    "\1\100\6\0\1\100\4\0\1\100\2\0\2\100\4\0"+
    "\1\100\1\101\5\100\2\0\1\100\1\0\3\100\30\0"+
    "\1\100\6\0\1\100\2\147\2\0\1\100\2\0\2\100"+
    "\4\0\1\150\1\151\5\150\2\0\1\150\1\0\3\150"+
    "\30\0\1\150\6\0\1\150\4\0\1\150\2\0\2\150"+
    "\52\0\3\44\27\0\1\152\17\0\2\44\6\0\2\44"+
    "\12\0\2\44\20\0\1\153\1\154\5\153\2\0\1\153"+
    "\1\0\3\153\30\0\1\153\6\0\1\153\4\0\1\153"+
    "\2\0\2\153\4\0\1\155\1\156\5\155\2\0\1\155"+
    "\1\0\3\155\30\0\1\155\6\0\1\155\4\0\1\155"+
    "\2\0\2\155\6\0\1\113\70\0\1\113\1\114\5\113"+
    "\2\0\1\113\1\0\3\113\30\0\1\113\6\0\1\113"+
    "\4\0\1\113\2\0\2\113\6\0\1\117\72\0\1\121"+
    "\131\0\2\157\65\0\2\160\36\0\1\125\72\0\1\127"+
    "\146\0\2\161\13\0\1\127\1\130\5\127\2\0\1\127"+
    "\1\0\3\127\30\0\1\127\6\0\1\127\4\0\1\127"+
    "\2\0\2\127\4\0\1\127\1\130\5\127\2\0\1\127"+
    "\1\0\3\127\30\0\1\127\6\0\1\127\2\162\2\0"+
    "\1\127\2\0\2\127\62\0\2\163\13\0\1\125\1\126"+
    "\5\125\2\0\1\125\1\0\3\125\30\0\1\125\6\0"+
    "\1\125\2\164\2\0\1\125\2\0\2\125\43\0\2\165"+
    "\42\0\1\166\7\0\1\166\64\0\1\167\7\0\1\167"+
    "\65\0\1\170\64\0\1\171\7\0\1\171\121\0\3\54"+
    "\27\0\1\172\17\0\2\54\6\0\2\54\12\0\2\54"+
    "\66\0\3\104\27\0\1\173\17\0\2\104\6\0\2\104"+
    "\12\0\2\104\22\0\1\150\72\0\1\153\72\0\1\155"+
    "\121\0\2\174\71\0\2\175\106\0\3\133\27\0\1\176"+
    "\17\0\2\133\6\0\2\133\12\0\2\133\66\0\3\66"+
    "\27\0\1\63\17\0\2\66\6\0\2\66\12\0\2\66"+
    "\107\0\2\177\13\0\1\200\7\0\1\200\2\0\1\200"+
    "\61\0\1\201\63\0\1\202\2\0\2\202\1\0\1\202"+
    "\10\0\2\202\1\0\1\202\1\0\1\202\1\0\1\202"+
    "\1\0\1\202\1\0\1\202\1\0\1\202\1\0\1\202"+
    "\1\0\1\202\3\0\1\202\1\0\1\202\4\0\1\202"+
    "\1\0\1\202\2\0\1\202\3\0\1\202\1\0\1\202"+
    "\35\0\2\203\105\0\2\203\26\0\1\204\26\0\2\205"+
    "\6\0\1\72\37\0\1\206\7\0\1\206\57\0\1\207"+
    "\7\0\1\207\15\0\2\31\40\0\1\202\2\0\2\202"+
    "\1\0\1\202\2\0\1\210\5\0\2\202\1\0\1\202"+
    "\1\0\1\202\1\0\1\202\1\0\1\202\1\0\1\202"+
    "\1\0\1\202\1\0\1\202\1\0\1\202\3\0\1\202"+
    "\1\0\1\202\4\0\1\202\1\0\1\202\2\0\1\202"+
    "\3\0\1\202\1\0\1\202\1\56\1\57\5\56\2\0"+
    "\1\56\1\0\3\56\30\0\1\56\6\0\1\56\4\0"+
    "\1\56\2\0\2\56\41\0\2\211\36\0\1\70\2\0"+
    "\1\72\1\71\5\0\1\70\71\0\1\70\130\0\2\67"+
    "\23\0\2\210\2\0\2\210\1\0\1\210\2\0\1\212"+
    "\5\0\2\210\1\0\1\210\1\0\1\210\1\0\1\210"+
    "\1\0\1\210\1\0\1\210\1\0\1\210\1\0\1\210"+
    "\1\0\1\210\3\0\1\210\1\0\2\210\3\0\1\210"+
    "\1\0\1\210\2\0\1\210\3\0\1\210\1\0\1\210"+
    "\25\0\2\213\2\214\115\0\1\215\56\0\2\216\63\0"+
    "\2\217\113\0\1\215\12\0\1\220\45\0\2\221\55\0"+
    "\2\222\107\0\2\223\61\0\2\223\73\0\2\224\47\0"+
    "\1\72\57\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7198];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\4\1\1\11\1\1\1\11\1\1\25\0\1\11"+
    "\1\1\1\0\1\1\12\0\1\11\1\1\2\0\2\1"+
    "\4\0\1\11\7\0\1\11\1\1\1\0\1\1\7\0"+
    "\1\11\2\1\1\0\1\11\1\1\1\11\1\1\2\0"+
    "\1\11\1\1\1\11\1\1\1\0\1\1\15\0\1\11"+
    "\2\1\1\11\1\1\1\11\1\1\12\0\1\11\2\1"+
    "\2\0\1\1\21\0\1\11\4\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[148];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
	
	/* Custom java code */

    @Override
	public String language() { return "IT"; }

	@Override
	public String version() { return "1.2"; }


	/* An empty default constructor is required to comply with LinkolnService */
	
	public Stopwords() { }
	
	@Override
	public final boolean run() {
		
		try {
			
			yyreset(new StringReader(getInput()));
			yylex();
			
		} catch (IOException e) {

			e.printStackTrace();
			return false;
		}
		
		return true;
	}
	
	@Override
	protected void addValue() {
	
		//annotationEntity.setValue("value");
	} 



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Stopwords(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 382) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return YYEOF;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { addText(yytext());
	position++;
            }
          case 24: break;
          case 2: 
            { addText(yytext());
		position++;
            }
          case 25: break;
          case 3: 
            { annotate(new Stopword(), "TO", true, true);
            }
          case 26: break;
          case 4: 
            { annotate(new Stopword(), "OR", true, true);
            }
          case 27: break;
          case 5: 
            { annotate(new Stopword(), "DET", true, false);
            }
          case 28: break;
          case 6: 
            { annotate(new Stopword(), "OF", true, false);
            }
          case 29: break;
          case 7: 
            { annotate(new Stopword(), "AND", true, true);
            }
          case 30: break;
          case 8: 
            { annotate(new Stopword(), "ON", true, true);
            }
          case 31: break;
          case 9: 
            { annotate(new Stopword(), "INDET", true, true);
            }
          case 32: break;
          case 10: 
            { annotate(new Stopword(), "INDET", true, false);
            }
          case 33: break;
          case 11: 
            { annotate(new Stopword(), "IN", true, true);
            }
          case 34: break;
          case 12: 
            { annotate(new Stopword(), "DET", true, true);
            }
          case 35: break;
          case 13: 
            { annotate(new Stopword(), "OF", true, true);
            }
          case 36: break;
          case 14: 
            { annotate(new Stopword(), "FROM", true, true);
            }
          case 37: break;
          case 15: 
            { annotate(new Stopword(), "ACROSS", true, true);
            }
          case 38: break;
          case 16: 
            { annotate(new Stopword(), "TO", true, false);
            }
          case 39: break;
          case 17: 
            { annotate(new Stopword(), "", true, true);
            }
          case 40: break;
          case 18: 
            { annotate(new Stopword(), "WITH", true, true);
            }
          case 41: break;
          case 19: 
            { addText(yytext());
		position--; //account for the following {LKN_C} character
		yybegin(YYINITIAL);
            }
          case 42: break;
          case 20: 
            { annotate(new Stopword(), "IN", true, false);
            }
          case 43: break;
          case 21: 
            { annotate(new Stopword(), "ON", true, false);
            }
          case 44: break;
          case 22: 
            { annotate(new Stopword(), "FROM", true, false);
            }
          case 45: break;
          case 23: 
            { addText(yytext()); 
	yybegin(lkn);
            }
          case 46: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This is a standalone scanner, it will print any unmatched
   * text to System.out unchanged.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java Stopwords [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          java.nio.charset.Charset.forName(encodingName); // Side-effect: is encodingName valid? 
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        Stopwords scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new Stopwords(reader);
          while ( !scanner.zzAtEOF ) scanner.yylex();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
